# Generated by Django 4.1 on 2022-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0003_brandsmodel_homebrandheadingsmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAirModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
