# Generated by Django 4.0.4 on 2022-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0003_brandsmodel_homebrandheadingsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAirModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
