# Generated by Django 4.1 on 2022-09-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0004_sairmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=250)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("link_in", models.URLField()),
            ],
        ),
    ]
