# Generated by Django 4.1 on 2022-09-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0007_rename_catalaguemodel_catalogmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
