# Generated by Django 4.1 on 2022-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0008_techpagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techpagemodel",
            name="image",
            field=models.ImageField(
                blank=True, default="image", null=True, upload_to=""
            ),
        ),
    ]
