# Generated by Django 4.1 on 2022-09-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0009_alter_techpagemodel_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalogmodel",
            old_name="heading",
            new_name="Heading",
        ),
        migrations.RenameField(
            model_name="catalogmodel",
            old_name="year",
            new_name="years",
        ),
    ]
