# Generated by Django 4.1 on 2022-09-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0010_rename_heading_catalogmodel_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandsmodel",
            name="image",
            field=models.ImageField(
                blank=True, default="image", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="catalogmodel",
            name="image",
            field=models.ImageField(
                blank=True, default="image", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="slidersimagesmodel",
            name="image",
            field=models.ImageField(
                blank=True, default="image", null=True, upload_to=""
            ),
        ),
    ]
