# Generated by Django 4.1 on 2022-09-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Admin_dashboard",
            "0011_alter_brandsmodel_image_alter_catalogmodel_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
