# Generated by Django 4.1 on 2022-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0012_corporatemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAirModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="image", null=True, upload_to=""
                    ),
                ),
                ("seriesname", models.CharField(blank=True, max_length=250, null=True)),
                ("seriesnumber", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
