# Generated by Django 4.1 on 2022-09-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0013_sairmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=250, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="image", null=True, upload_to=""
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
