# Generated by Django 4.1 on 2022-09-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0014_newsmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsmodel",
            old_name="heading",
            new_name="description",
        ),
    ]
