# Generated by Django 4.1 on 2022-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_dashboard", "0016_rename_description_newsmodel_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsmodel",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
